-- Business CMS (/cms): clients, orders, payments, expenses, push subscriptions.
-- Additive. Does not touch products or inquiries from schema.sql.
-- Run schema.sql first: this file reuses public.set_updated_at().
--
-- Money is bigint whole rupees. The CHECK lists mirror src/content/cms.ts by
-- hand; change one and you must change the other.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 140),
  type text not null default 'individual' check (type in ('individual', 'showroom', 'factory', 'institution')),
  phone text check (char_length(phone) between 7 and 30),
  address text check (char_length(address) <= 400),
  notes text check (char_length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity unique,
  client_id uuid not null references public.clients(id) on delete restrict,
  site_label text check (char_length(site_label) <= 80),
  title text not null check (char_length(title) between 2 and 200),
  description text not null default '' check (char_length(description) <= 4000),
  delivery_address text check (char_length(delivery_address) <= 400),
  contact_phone text check (char_length(contact_phone) between 7 and 30),
  total_amount bigint not null default 0 check (total_amount between 0 and 999999999999),
  order_date date not null default current_date,
  expected_date date,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'ready', 'delivered', 'cancelled')),
  image_paths text[] not null default '{}'::text[] check (cardinality(image_paths) <= 12),
  notes text check (char_length(notes) <= 4000),
  reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  amount bigint not null check (amount > 0 and amount <= 999999999999),
  paid_on date not null default current_date,
  method text not null default 'cash' check (method in ('cash', 'bank', 'easypaisa', 'jazzcash', 'cheque', 'other')),
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  spent_on date not null default current_date,
  category text not null check (category in ('material', 'labor', 'daily_wages', 'hardware', 'polish', 'kitchen', 'misc', 'other')),
  amount bigint not null check (amount > 0 and amount <= 999999999999),
  note text check (char_length(note) <= 400),
  order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  label text check (char_length(label) <= 80),
  created_at timestamptz not null default now()
);

create index if not exists clients_name_idx on public.clients (name);
create index if not exists orders_client_idx on public.orders (client_id, created_at desc);
create index if not exists orders_status_idx on public.orders (status, expected_date);
create index if not exists orders_due_idx on public.orders (expected_date) where reminder_sent_at is null;
create index if not exists order_payments_order_idx on public.order_payments (order_id, paid_on desc);
create index if not exists expenses_spent_idx on public.expenses (spent_on desc);
create index if not exists expenses_order_idx on public.expenses (order_id) where order_id is not null;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();


-- Row level security ---------------------------------------------------------
-- Every CMS table is admin only. Nothing here is readable by anon.

alter table public.clients enable row level security;
alter table public.orders enable row level security;
alter table public.order_payments enable row level security;
alter table public.expenses enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "Admins manage clients" on public.clients;
create policy "Admins manage clients" on public.clients for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders" on public.orders for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage order payments" on public.order_payments;
create policy "Admins manage order payments" on public.order_payments for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage expenses" on public.expenses;
create policy "Admins manage expenses" on public.expenses for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

-- A subscription belongs to one device of one admin, so scope it to the owner.
drop policy if exists "Admins manage own push subscriptions" on public.push_subscriptions;
create policy "Admins manage own push subscriptions" on public.push_subscriptions for all to authenticated
using (
  user_id = (select auth.uid())
  and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin'
)
with check (
  user_id = (select auth.uid())
  and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin'
);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.clients to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, update, delete on public.order_payments to authenticated;
grant select, insert, update, delete on public.expenses to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- Storage --------------------------------------------------------------------
-- Order photos are customer documents. Unlike product-images this bucket is
-- private; the app hands out short-lived signed URLs.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('order-images', 'order-images', false, 8388608, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('backups', 'backups', false, 52428800, array['application/json'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

drop policy if exists "Admins read order images" on storage.objects;
create policy "Admins read order images" on storage.objects for select to authenticated
using (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins upload order images" on storage.objects;
create policy "Admins upload order images" on storage.objects for insert to authenticated
with check (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins delete order images" on storage.objects;
create policy "Admins delete order images" on storage.objects for delete to authenticated
using (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins read backups" on storage.objects;
create policy "Admins read backups" on storage.objects for select to authenticated
using (bucket_id = 'backups' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');
