-- Business CMS (/cms): clients, orders, payments, expenses, push subscriptions.
-- Additive. Does not touch products or inquiries from schema.sql.
-- Run schema.sql first: this file reuses public.set_updated_at().
--
-- Money is bigint whole rupees. The CHECK lists mirror src/content/cms.ts by
-- hand; change one and you must change the other.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 140),
  type text not null default 'individual' check (type in ('individual', 'showroom', 'factory', 'institution')),
  phone text check (char_length(phone) between 7 and 30),
  address text check (char_length(address) <= 400),
  notes text check (char_length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity unique,
  client_id uuid not null references public.clients(id) on delete restrict,
  site_label text check (char_length(site_label) <= 80),
  title text not null check (char_length(title) between 2 and 200),
  description text not null default '' check (char_length(description) <= 4000),
  delivery_address text check (char_length(delivery_address) <= 400),
  contact_phone text check (char_length(contact_phone) between 7 and 30),
  total_amount bigint not null default 0 check (total_amount between 0 and 999999999999),
  order_date date not null default current_date,
  expected_date date,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'ready', 'completed', 'delivered', 'cancelled')),
  image_paths text[] not null default '{}'::text[] check (cardinality(image_paths) <= 12),
  notes text check (char_length(notes) <= 4000),
  reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  amount bigint not null check (amount > 0 and amount <= 999999999999),
  paid_on date not null default current_date,
  method text not null default 'cash' check (method in ('cash', 'bank', 'easypaisa', 'jazzcash', 'cheque', 'other')),
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  spent_on date not null default current_date,
  category text not null check (char_length(btrim(category)) between 1 and 80),
  amount bigint not null check (amount > 0 and amount <= 999999999999),
  note text check (char_length(note) <= 400),
  order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  label text check (char_length(label) <= 80),
  created_at timestamptz not null default now()
);

create index if not exists clients_name_idx on public.clients (name);
create index if not exists orders_client_idx on public.orders (client_id, created_at desc);
create index if not exists orders_status_idx on public.orders (status, expected_date);
create index if not exists orders_due_idx on public.orders (expected_date) where reminder_sent_at is null;
create index if not exists order_payments_order_idx on public.order_payments (order_id, paid_on desc);
create index if not exists expenses_spent_idx on public.expenses (spent_on desc);
create index if not exists expenses_order_idx on public.expenses (order_id) where order_id is not null;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();


-- Row level security ---------------------------------------------------------
-- Every CMS table is admin only. Nothing here is readable by anon.

alter table public.clients enable row level security;
alter table public.orders enable row level security;
alter table public.order_payments enable row level security;
alter table public.expenses enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "Admins manage clients" on public.clients;
create policy "Admins manage clients" on public.clients for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders" on public.orders for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage order payments" on public.order_payments;
create policy "Admins manage order payments" on public.order_payments for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins manage expenses" on public.expenses;
create policy "Admins manage expenses" on public.expenses for all to authenticated
using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin')
with check (coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

-- A subscription belongs to one device of one admin, so scope it to the owner.
drop policy if exists "Admins manage own push subscriptions" on public.push_subscriptions;
create policy "Admins manage own push subscriptions" on public.push_subscriptions for all to authenticated
using (
  user_id = (select auth.uid())
  and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin'
)
with check (
  user_id = (select auth.uid())
  and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin'
);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.clients to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, update, delete on public.order_payments to authenticated;
grant select, insert, update, delete on public.expenses to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- Storage --------------------------------------------------------------------
-- Order photos are customer documents. Unlike product-images this bucket is
-- private; the app hands out short-lived signed URLs.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('order-images', 'order-images', false, 8388608, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('backups', 'backups', false, 52428800, array['application/json'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

drop policy if exists "Admins read order images" on storage.objects;
create policy "Admins read order images" on storage.objects for select to authenticated
using (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins upload order images" on storage.objects;
create policy "Admins upload order images" on storage.objects for insert to authenticated
with check (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins delete order images" on storage.objects;
create policy "Admins delete order images" on storage.objects for delete to authenticated
using (bucket_id = 'order-images' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

drop policy if exists "Admins read backups" on storage.objects;
create policy "Admins read backups" on storage.objects for select to authenticated
using (bucket_id = 'backups' and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin');

-- Upgrade an existing CMS. Also appended to cms-schema.sql for fresh installs.
-- Existing order amounts/payments are preserved; the new UI does not use them.
begin;

alter table public.orders add column if not exists items jsonb not null default '[]'::jsonb;
-- Urgent orders carry a red mark through the orders tree. Existing rows are not urgent.
alter table public.orders add column if not exists urgent boolean not null default false;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('pending', 'in_progress', 'ready', 'completed', 'delivered', 'cancelled'));

create or replace function public.cms_valid_order_items(entries jsonb)
returns boolean language plpgsql immutable security invoker set search_path = '' as $$
declare entry jsonb;
begin
  if jsonb_typeof(entries) <> 'array' or jsonb_array_length(entries) > 100 then return false; end if;
  for entry in select value from jsonb_array_elements(entries) loop
    if not (entry ?& array['id','name','quantity','status','notes']) then return false; end if;
    if jsonb_typeof(entry->'id') <> 'string' or jsonb_typeof(entry->'quantity') <> 'number' or jsonb_typeof(entry->'status') <> 'string' then return false; end if;
    if jsonb_typeof(entry->'name') <> 'string' or char_length(btrim(entry->>'name')) not between 1 and 200
      or jsonb_typeof(entry->'notes') <> 'string' or char_length(entry->>'notes') > 1000
      or (entry->>'quantity') !~ '^[0-9]+$' or (entry->>'quantity')::bigint not between 1 and 10000
      or (entry->>'status') not in ('pending','in_progress','ready','completed','delivered','cancelled')
      or (entry->>'id') !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      then return false; end if;
  end loop;
  return true;
exception when others then return false;
end;
$$;
alter table public.orders drop constraint if exists orders_items_check;
alter table public.orders add constraint orders_items_check check (public.cms_valid_order_items(items));

alter table public.expenses drop constraint if exists expenses_category_check;
alter table public.expenses add constraint expenses_category_check check (char_length(btrim(category)) between 1 and 80);

create table if not exists public.balance_entries (
  id uuid primary key default gen_random_uuid(),
  received_on date not null default (now() at time zone 'Asia/Karachi')::date,
  amount bigint not null check (amount between 1 and 999999999999),
  note text not null check (char_length(btrim(note)) between 2 and 400),
  created_at timestamptz not null default now()
);

create table if not exists public.labour_entries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 2 and 140),
  period date not null check (extract(day from period) = 1),
  paid_on date not null default (now() at time zone 'Asia/Karachi')::date,
  salary bigint not null check (salary between 0 and 999999999999),
  total_amount bigint not null check (total_amount between 0 and 999999999999),
  advance bigint not null default 0 check (advance between 0 and 999999999999),
  salary_paid bigint not null default 0 check (salary_paid between 0 and 999999999999),
  leaves integer not null default 0 check (leaves between 0 and 31),
  notes text check (char_length(notes) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (advance + salary_paid <= total_amount)
);

-- Validates the lines and computes the stored bigint total in one atomic write.
create or replace function public.cms_invoice_total(entries jsonb)
returns bigint language plpgsql immutable security invoker set search_path = '' as $$
declare entry jsonb; total bigint := 0;
begin
  if jsonb_typeof(entries) <> 'array' or jsonb_array_length(entries) not between 1 and 100 then
    raise exception 'Invalid invoice items';
  end if;
  for entry in select value from jsonb_array_elements(entries) loop
    if not (entry ?& array['id','item','quantity','amount','source']) then raise exception 'Invalid invoice item'; end if;
    if jsonb_typeof(entry->'id') <> 'string' or jsonb_typeof(entry->'quantity') <> 'number' or jsonb_typeof(entry->'amount') <> 'number' then raise exception 'Invalid invoice item'; end if;
    if jsonb_typeof(entry->'item') <> 'string' or char_length(btrim(entry->>'item')) not between 1 and 200
      or jsonb_typeof(entry->'source') <> 'string' or char_length(btrim(entry->>'source')) not between 1 and 80
      or (entry->>'quantity') !~ '^[0-9]+$' or (entry->>'quantity')::bigint not between 1 and 10000
      or (entry->>'amount') !~ '^[0-9]+$' or (entry->>'amount')::bigint not between 0 and 999999999999
      or (entry->>'id') !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      then raise exception 'Invalid invoice item'; end if;
    total := total + (entry->>'amount')::bigint * (entry->>'quantity')::bigint;
  end loop;
  if total not between 1 and 999999999999 then raise exception 'Invalid invoice total'; end if;
  return total;
end;
$$;

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_no bigint generated always as identity unique,
  client_id uuid not null references public.clients(id) on delete restrict,
  client_name text not null check (char_length(btrim(client_name)) between 2 and 140),
  client_address text check (char_length(client_address) <= 400),
  client_phone text check (char_length(client_phone) <= 30),
  issued_on date not null default (now() at time zone 'Asia/Karachi')::date,
  items jsonb not null,
  total_amount bigint generated always as (public.cms_invoice_total(items)) stored,
  notes text check (char_length(notes) <= 2000),
  status text not null default 'issued' check (status in ('issued','void')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Labour payslip inputs. Total is computed from these by labourTotals() in
-- src/lib/accounting-core.ts and written by the one save path, so the sheet
-- cannot show a total that disagrees with the salary and hours behind it.
alter table public.labour_entries add column if not exists per_day_salary bigint not null default 0
  check (per_day_salary between 0 and 999999999999);
alter table public.labour_entries add column if not exists ot_hours integer not null default 0
  check (ot_hours between 0 and 1000);
alter table public.labour_entries add column if not exists ot_rate bigint not null default 0
  check (ot_rate between 0 and 999999999999);
alter table public.labour_entries add column if not exists deduction bigint not null default 0
  check (deduction between 0 and 999999999999);
-- Deductions can now exceed earnings, and what has been paid can exceed a
-- reduced total, so both of the original guards on total_amount are wrong.
alter table public.labour_entries drop constraint if exists labour_entries_check;
alter table public.labour_entries drop constraint if exists labour_entries_total_amount_check;
alter table public.labour_entries add constraint labour_entries_total_amount_check
  check (total_amount between -999999999999 and 999999999999);

create index if not exists balance_entries_date_idx on public.balance_entries (received_on desc, id);
create index if not exists labour_entries_period_idx on public.labour_entries (period, name, id);
create index if not exists labour_entries_paid_idx on public.labour_entries (paid_on);
create index if not exists invoices_client_date_idx on public.invoices (client_id, issued_on desc, id);
create index if not exists invoices_date_idx on public.invoices (issued_on desc, id);

drop trigger if exists labour_entries_updated_at on public.labour_entries;
create trigger labour_entries_updated_at before update on public.labour_entries for each row execute function public.set_updated_at();
drop trigger if exists invoices_updated_at on public.invoices;
create trigger invoices_updated_at before update on public.invoices for each row execute function public.set_updated_at();

alter table public.balance_entries enable row level security;
alter table public.labour_entries enable row level security;
alter table public.invoices enable row level security;

drop policy if exists "Admins manage balances" on public.balance_entries;
create policy "Admins manage balances" on public.balance_entries for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');
drop policy if exists "Admins manage labour" on public.labour_entries;
create policy "Admins manage labour" on public.labour_entries for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');
drop policy if exists "Admins manage invoices" on public.invoices;
create policy "Admins manage invoices" on public.invoices for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

grant select, insert, update, delete on public.balance_entries, public.labour_entries, public.invoices to authenticated;
grant usage, select on sequence public.invoices_invoice_no_seq to authenticated;
revoke all on function public.cms_invoice_total(jsonb), public.cms_valid_order_items(jsonb) from public, anon;
grant execute on function public.cms_invoice_total(jsonb), public.cms_valid_order_items(jsonb) to authenticated, service_role;

-- SQL sums cover every record, independent of the API's row limit. Return text
-- so arbitrarily large all-time values survive JSON without precision loss.
create or replace function public.cms_financial_totals()
returns jsonb language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'added', (select coalesce(sum(amount),0)::text from public.balance_entries),
    'expenses', (select coalesce(sum(amount),0)::text from public.expenses),
    'labourPaid', (select coalesce(sum(advance + salary_paid),0)::text from public.labour_entries),
    'sales', (select coalesce(sum(total_amount),0)::text from public.invoices where status = 'issued'),
    'openOrders', (select count(*) from public.orders where status in ('pending','in_progress','ready'))
  );
$$;
revoke all on function public.cms_financial_totals() from public, anon;
grant execute on function public.cms_financial_totals() to authenticated;

notify pgrst, 'reload schema';
commit;
