-- Factory inventory (/factory/inventory): stock items, their code, and a photo.
-- Additive. Run schema.sql and cms-schema.sql first: this reuses set_updated_at().
--
-- Stock is deducted by factory invoices. An invoice line carrying a `code` that
-- matches an item here reduces its quantity by the line quantity, floored at
-- zero — a sale that already happened is never refused, it is reported.

begin;

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  item_no bigint generated by default as identity unique,
  code text not null check (char_length(btrim(code)) between 1 and 40),
  name text not null check (char_length(btrim(name)) between 1 and 200),
  quantity integer not null default 0 check (quantity between 0 and 1000000),
  image_path text check (char_length(image_path) <= 400),
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Codes are matched case-insensitively when an invoice deducts stock, so they
-- must be unique the same way: "ptf-01" and "PTF-01" are the same item.
create unique index if not exists inventory_items_code_key on public.inventory_items (upper(btrim(code)));
create index if not exists inventory_items_name_idx on public.inventory_items (name);
create index if not exists inventory_items_empty_idx on public.inventory_items (item_no) where quantity = 0;

drop trigger if exists inventory_items_updated_at on public.inventory_items;
create trigger inventory_items_updated_at before update on public.inventory_items
  for each row execute function public.set_updated_at();

alter table public.inventory_items enable row level security;
drop policy if exists "Admins manage inventory" on public.inventory_items;
create policy "Admins manage inventory" on public.inventory_items for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

grant select, insert, update, delete on public.inventory_items to authenticated;
grant usage, select on sequence public.inventory_items_item_no_seq to authenticated;

-- Private, like order photos: stock photography is internal, not the catalogue.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('inventory-images', 'inventory-images', false, 8388608, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins read inventory images" on storage.objects;
create policy "Admins read inventory images" on storage.objects for select to authenticated
using (bucket_id = 'inventory-images' and coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');
drop policy if exists "Admins upload inventory images" on storage.objects;
create policy "Admins upload inventory images" on storage.objects for insert to authenticated
with check (bucket_id = 'inventory-images' and coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');
drop policy if exists "Admins delete inventory images" on storage.objects;
create policy "Admins delete inventory images" on storage.objects for delete to authenticated
using (bucket_id = 'inventory-images' and coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

notify pgrst, 'reload schema';
commit;
