-- Shop ledger (/shop): counter sales, shop invoices and shop expenses for
-- Pak Tribal Furniture. Additive. Run schema.sql then cms-schema.sql first:
-- this file reuses public.set_updated_at() and public.cms_invoice_total().
--
-- Money is bigint whole rupees. The shop's books are separate from the
-- factory's: shop net profit deducts shop_expenses, never public.expenses.
--
-- A sale row's `sale_price` (per unit) is the truth. Invoice-drafted rows take
-- it from the invoice; manual rows have it computed by manualSalePrice() in
-- src/lib/accounting-core.ts, with margin_pct/discount_pct kept as a record of
-- how the price was reached. `cost` is null until the purchase price is known.

begin;

-- Line subtotal less a whole-percentage discount. Mirrors invoiceDiscount().
create or replace function public.cms_shop_invoice_total(entries jsonb, discount_pct integer)
returns bigint language plpgsql immutable security invoker set search_path = '' as $$
declare subtotal bigint;
begin
  if discount_pct is null or discount_pct not between 0 and 100 then
    raise exception 'Invalid invoice discount';
  end if;
  subtotal := public.cms_invoice_total(entries);
  return subtotal - (subtotal * discount_pct + 50) / 100;
end;
$$;

create table if not exists public.shop_invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_no bigint generated always as identity unique,
  -- A counter sale has no client record, so the customer is typed in full.
  customer_name text not null check (char_length(btrim(customer_name)) between 2 and 140),
  customer_phone text check (char_length(customer_phone) <= 30),
  customer_address text check (char_length(customer_address) <= 400),
  issued_on date not null default (now() at time zone 'Asia/Karachi')::date,
  items jsonb not null,
  notes text check (char_length(notes) <= 2000),
  status text not null default 'issued' check (status in ('issued','void')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade an existing shop: add the discount, then regenerate the total from
-- it. total_amount is a generated column, so dropping and re-adding it
-- recomputes every row rather than losing data.
alter table public.shop_invoices add column if not exists discount_pct integer not null default 0
  check (discount_pct between 0 and 100);
alter table public.shop_invoices drop column if exists total_amount;
alter table public.shop_invoices add column total_amount bigint
  generated always as (public.cms_shop_invoice_total(items, discount_pct)) stored;

create table if not exists public.shop_sales (
  id uuid primary key default gen_random_uuid(),
  sale_no bigint generated by default as identity unique,
  sold_on date not null default (now() at time zone 'Asia/Karachi')::date,
  name text not null check (char_length(btrim(name)) between 1 and 200),
  quantity integer not null default 1 check (quantity between 1 and 10000),
  sale_price bigint not null check (sale_price between 0 and 999999999999),
  cost bigint check (cost between 0 and 999999999999),
  margin_pct integer check (margin_pct between 0 and 1000),
  discount_pct integer check (discount_pct between 0 and 100),
  -- Set for rows drafted from an invoice. Voiding an invoice leaves the row.
  invoice_id uuid references public.shop_invoices(id) on delete set null,
  -- Set when the customer brings the item back; the row then leaves the totals.
  returned_on date,
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade an existing shop ledger to the invoice-driven shape. Additive and
-- idempotent, so re-running this file never drops a row. The first shape
-- stored cost + margin + a rupee discount and derived the sale price; the sale
-- price is now stored, because an invoice-drafted row gets it from the invoice.
alter table public.shop_sales add column if not exists quantity integer not null default 1
  check (quantity between 1 and 10000);
alter table public.shop_sales add column if not exists sale_price bigint not null default 0
  check (sale_price between 0 and 999999999999);
alter table public.shop_sales add column if not exists discount_pct integer
  check (discount_pct between 0 and 100);
alter table public.shop_sales add column if not exists invoice_id uuid
  references public.shop_invoices(id) on delete set null;
alter table public.shop_sales alter column sale_price drop default;
-- cost is unknown on a draft row, and margin is only a record of manual pricing.
alter table public.shop_sales alter column cost drop not null;
alter table public.shop_sales alter column margin_pct drop not null;
alter table public.shop_sales alter column margin_pct drop default;
-- The rupee discount and the CHECK that guarded it are both superseded.
alter table public.shop_sales drop constraint if exists shop_sales_sale_not_negative;
alter table public.shop_sales drop column if exists discount;

-- The shop's own expenses. Deliberately not public.expenses: that table is the
-- factory's, and mixing the two made shop profit meaningless.
create table if not exists public.shop_expenses (
  id uuid primary key default gen_random_uuid(),
  spent_on date not null default (now() at time zone 'Asia/Karachi')::date,
  category text not null check (char_length(btrim(category)) between 1 and 80),
  amount bigint not null check (amount > 0 and amount <= 999999999999),
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now()
);

create index if not exists shop_sales_date_idx on public.shop_sales (sold_on desc, sale_no desc);
create index if not exists shop_sales_draft_idx on public.shop_sales (sale_no) where cost is null;
create index if not exists shop_sales_invoice_idx on public.shop_sales (invoice_id) where invoice_id is not null;
create index if not exists shop_invoices_date_idx on public.shop_invoices (issued_on desc, invoice_no desc);
create index if not exists shop_expenses_date_idx on public.shop_expenses (spent_on desc, id);

drop trigger if exists shop_sales_updated_at on public.shop_sales;
create trigger shop_sales_updated_at before update on public.shop_sales for each row execute function public.set_updated_at();
drop trigger if exists shop_invoices_updated_at on public.shop_invoices;
create trigger shop_invoices_updated_at before update on public.shop_invoices for each row execute function public.set_updated_at();

alter table public.shop_sales enable row level security;
alter table public.shop_invoices enable row level security;
alter table public.shop_expenses enable row level security;

drop policy if exists "Admins manage shop sales" on public.shop_sales;
create policy "Admins manage shop sales" on public.shop_sales for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

drop policy if exists "Admins manage shop invoices" on public.shop_invoices;
create policy "Admins manage shop invoices" on public.shop_invoices for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

drop policy if exists "Admins manage shop expenses" on public.shop_expenses;
create policy "Admins manage shop expenses" on public.shop_expenses for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

grant select, insert, update, delete on public.shop_sales, public.shop_invoices, public.shop_expenses to authenticated;
grant usage, select on sequence public.shop_sales_sale_no_seq to authenticated;
grant usage, select on sequence public.shop_invoices_invoice_no_seq to authenticated;
revoke all on function public.cms_shop_invoice_total(jsonb, integer) from public, anon;
grant execute on function public.cms_shop_invoice_total(jsonb, integer) to authenticated, service_role;

notify pgrst, 'reload schema';
commit;
