-- Shop ledger (/shop): counter sales and shop invoices for Pak Tribal Furniture.
-- Additive. Run schema.sql then cms-schema.sql first: this file reuses
-- public.set_updated_at() and public.cms_invoice_total().
--
-- Money is bigint whole rupees. Marked price, sale and profit are DERIVED, not
-- stored — shopSaleAmounts() in src/lib/accounting-core.ts is the one formula.
-- The CHECK below repeats its integer rounding so the two cannot disagree:
--   marked = cost + (cost * margin_pct + 50) / 100      (bigint division)
--   sale   = marked - discount
--   profit = sale - cost

begin;

create table if not exists public.shop_sales (
  id uuid primary key default gen_random_uuid(),
  sale_no bigint generated by default as identity unique,
  sold_on date not null default (now() at time zone 'Asia/Karachi')::date,
  name text not null check (char_length(btrim(name)) between 1 and 200),
  cost bigint not null check (cost between 0 and 999999999999),
  margin_pct integer not null default 40 check (margin_pct between 0 and 1000),
  discount bigint not null default 0 check (discount between 0 and 999999999999),
  -- Set when the customer brings the item back; the row then leaves the totals.
  returned_on date,
  note text check (char_length(note) <= 400),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_sales_sale_not_negative check (discount <= cost + (cost * margin_pct + 50) / 100)
);

create table if not exists public.shop_invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_no bigint generated always as identity unique,
  -- A counter sale has no client record, so the customer is typed in full.
  customer_name text not null check (char_length(btrim(customer_name)) between 2 and 140),
  customer_phone text check (char_length(customer_phone) <= 30),
  customer_address text check (char_length(customer_address) <= 400),
  issued_on date not null default (now() at time zone 'Asia/Karachi')::date,
  items jsonb not null,
  total_amount bigint generated always as (public.cms_invoice_total(items)) stored,
  notes text check (char_length(notes) <= 2000),
  status text not null default 'issued' check (status in ('issued','void')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shop_sales_date_idx on public.shop_sales (sold_on desc, sale_no desc);
create index if not exists shop_sales_open_idx on public.shop_sales (sale_no) where returned_on is null;
create index if not exists shop_invoices_date_idx on public.shop_invoices (issued_on desc, invoice_no desc);

drop trigger if exists shop_sales_updated_at on public.shop_sales;
create trigger shop_sales_updated_at before update on public.shop_sales for each row execute function public.set_updated_at();
drop trigger if exists shop_invoices_updated_at on public.shop_invoices;
create trigger shop_invoices_updated_at before update on public.shop_invoices for each row execute function public.set_updated_at();

alter table public.shop_sales enable row level security;
alter table public.shop_invoices enable row level security;

drop policy if exists "Admins manage shop sales" on public.shop_sales;
create policy "Admins manage shop sales" on public.shop_sales for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

drop policy if exists "Admins manage shop invoices" on public.shop_invoices;
create policy "Admins manage shop invoices" on public.shop_invoices for all to authenticated
using (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin')
with check (coalesce((select auth.jwt()->'app_metadata'->>'role'), '') = 'admin');

grant select, insert, update, delete on public.shop_sales, public.shop_invoices to authenticated;
grant usage, select on sequence public.shop_sales_sale_no_seq to authenticated;
grant usage, select on sequence public.shop_invoices_invoice_no_seq to authenticated;

notify pgrst, 'reload schema';
commit;
